apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configMapGenerator:
- name: benthos-k-cm
  labels: 
    app: benthos-noop
  behavior: create
  files:
  - ./benthos.yaml
