apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-aoa-appset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
      revision: HEAD
      directories:
      - path: guestbook-appOfApps/*
      - path: guestbook-appOfApps/parent.yaml
        exclude: true
  template:
    metadata:
      name: 'aoa-{{.path.basename}}'
      labels:
        pattern: aoa
    spec:
      project: default
      source:
        repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
