apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-admin-mgmt
  namespace: dev
  labels:
    project: admin-mgmt
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
      revision: HEAD
      files:
      - path: dev/admin-mgmt/**/kustomization.yaml
  template:
    metadata:
      name: 'dev-admin-mgmt-{{.path.basename}}'
      labels:
        project: admin-mgmt
    spec:
      project: dev
      source:
        repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
