apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-user-management
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    project: user-management
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
      revision: HEAD
      directories:
      - path: dev/user-management/*
  template:
    metadata:
      name: 'user-management-{{.path.basename}}'
      labels:
        project: user-management
    spec:
      project: dev
      source:
        repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
