apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: benthos-noop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
    path: benthos-noop
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
