apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: dev
spec:
  project: dev
  source:
    repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
    path: dev/guestbook
    targetRevision: HEAD
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: prod
spec:
  project: prod
  source:
    repoURL: https://github.com/eyad-kobatte/test-argocd-site.git
    path: prod/guestbook
    targetRevision: HEAD
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
